# ===================================
#  Grid Widget Configuration
# ===================================

dataSource: client
keyFrom: code
recordsPerPage: 6
handler: onChange

# toolbar:
    # buttons: grid_toolbar

columns:
    from:
        title: From
    to:
        title: To
